### PR TITLE
refactor "PropTypes" for React 15

### PR DESCRIPTION
**Pull request by Undeadlol1**
In order to suppress warnings in React 15, "PropTypes" must be used using "prop-types" package.

### CODE REVIEW

**Comment by dmytroyarmak** [comment]
Thanks @Undeadlol1

**Comment by Undeadlol1** [comment]
My pleasure.
Please don't forget to publish new versions of "react-ultimate-pagination" and "react-ultimate-pagination-material-ui" to npm.

**Comment by dmytroyarmak** [comment]
done

**Comment by Undeadlol1** [comment]
Thanks, much appreciated.

**Pull request merged**
