### PR TITLE
Supplying the rest of the props to the wrapper

### PR DESCRIPTION
**Pull request by jshthornton**
This PR allows the parent to pass down whatever props it cares for.
That will allow the wrapping component to determine how it wants to render its children, maybe add styles, etc.

### CODE REVIEW

**Comment by dmytroyarmak** [comment]
@jshthornton Thank you for your PR

What props exactly do you need for wrapper in your use case? Are `currentPage` and `totalPages` will be enough?

Also, can you please remove #b34b19d commit from this PR because `lib` and `dist` shouldn't be committed.

**Comment by jshthornton** [comment]
A lot of projects have adopted to use inline css over stylesheets. So styles would at least need to be passed in. So whilst we're at it we might as well let the developer choose what gets passed in.

On the lib and dist front, most repos now include these as it allows for forks to be used as a source without having to create their own npm repo. I agree it feels weird to include built files into source control.

**Comment by dmytroyarmak** [comment]
@jshthornton about inline CSS, you currently can write it inside your `<WrapperComponent>` implementation without props passing. The only difference that your styles will be static and they can depend neither on `currentPage` and `totalPages` not on a place in which you are using pagination component.

I'm not against this changes; I'm just looking for an example for this feature to add it to the documentation.

And about `lib` and `dist`, yeah,  it's ok to commit them in fork if you want to use a custom build of the library but I would like to avoid committing it to the main repo. These artifacts will make automatic conflict resolving impossible and also it will make repo much bigger.

**Comment by jshthornton** [comment]
Let's take for example doing basic themeing. I would write something along the lines of:
```
<Pagination
  style={{
    backgroundColor: '#000'
  }}
/>
```

Then in WrapperComponent you can write:
```
return (
  <div style={{
    ...props.style
  }}>
    {props.children}
  </div>
);
```

**Comment by dmytroyarmak** [comment]
Currently, this library supports only "static" customization of paginator, it means that you need to specify how components should look like when you are creating a pagination component.

For example, your case will look like:
```
const WrapperComponent = ({children}) => (
  <div style={{
    backgroundColor: '#000'
  }}>
   {children}
  </div>
);

...

const Pagination = createUltimatePagination({itemTypeToComponent, WrapperComponent});
```
And then use it like:
```
<Pagination/>
```

But, yeah, the dynamic customization is not possible without some props passing.

I see your point. But let me think about it more. I want to investigate If there are some cons of this approach, especially when using TypeScript or Flow.

**Pull request closed without merging**
